"""
Centralized constants for the Analytics module.
"""
from django.db.models import Q

# Trend thresholds
GROWTH_RATE_RISING = 20
GROWTH_RATE_INCREASING = 5
GROWTH_RATE_DECREASING = -5

# Forecasting Configuration
DEFAULT_FORECAST_DAYS = 7
DEFAULT_LOOKBACK_DAYS = 30
DEFAULT_CONFIDENCE_LEVEL = 0.95
TREND_UP_THRESHOLD = 1.1
TREND_DOWN_THRESHOLD = 0.9
TREND_STRICT_UP_THRESHOLD = 1.3
TREND_STRICT_DOWN_THRESHOLD = 0.7
TREND_SEVERE_THRESHOLD = 2.0
DEMAND_SAFETY_BUFFER = 1.2
TOP_DISEASES_BATCH_LIMIT = 20
REORDER_SAFETY_MULTIPLIER = 1.5

# ML Engine Weights
MA_WEIGHT_RECENT = 0.6
MA_WEIGHT_HISTORICAL = 0.4
EXPONENTIAL_SMOOTHING_ALPHA = 0.3
TIME_DECAY_WEIGHT_RECENT = 0.7
TIME_DECAY_WEIGHT_HISTORICAL = 0.3
TREND_WEIGHT_RECENT = 0.7
TREND_WEIGHT_HISTORICAL = 0.3

# Spike Detection Constants
Z_SCORE_THRESHOLD = 2.0
MIN_SPIKE_VOLUME = 1
BASELINE_DAYS = 7
MIN_STD_DEV = 0.5
SPIKE_CRITICAL_Z = 4.0
SPIKE_WARNING_Z = 3.0
OUTBREAK_MIN_DAYS = 3
OUTBREAK_MIN_CASES = 5
OUTBREAK_SCORE_CRITICAL = 100.0

# Display Limits
DEFAULT_TOP_DRUGS_LIMIT = 50
DEFAULT_TOP_MEDICINES_LIMIT = 10

# Rounding Precision
ROUNDING_PRECISION_USAGE = 4
ROUNDING_PRECISION_GROWTH = 2
ROUNDING_PRECISION_DEFAULT = 2

# Global filters for variants: 'Vari' or ends with ' V'
VARIANT_FILTERS = Q(disease__name__icontains='Vari') | Q(disease__name__endswith=' V')

# Cache Timeouts (in seconds)
ANALYTICS_CACHE_TIMEOUT = 300
ALERTS_CACHE_TIMEOUT = 60
STATIC_DATA_CACHE_TIMEOUT = 86400  # 24 hours
DASHBOARD_CACHE_TIMEOUT = 300
OUTBREAK_SPIKE_LOOKBACK_DAYS = 14
