# Generated by Django 6.0.3 on 2026-03-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='appointment_datetime',
        ),
        migrations.AlterField(
            model_name='disease',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
