# Generated by Django 6.0.3 on 2026-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_performance_indexes'),
        ('core', '0002_alter_doctor_first_name_alter_doctor_last_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_datetime', 'disease'], name='analytics_a_appoint_cca351_idx'),
        ),
    ]
