# Generated by Django 6.0.3 on 2026-03-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_prescriptionline_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmaster',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
    ]
