# Generated by Django 6.0.3 on 2026-04-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugmaster',
            name='drug_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='generic_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prescriptionline',
            name='quantity',
            field=models.IntegerField(db_index=True),
        ),
    ]
