# Generated by Django 6.0.3 on 2026-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_appointment_analytics_a_appoint_cca351_idx'),
        ('inventory', '0003_add_prescription_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prescriptionline',
            index=models.Index(fields=['prescription_date', 'drug', 'disease'], name='inventory_p_prescri_0bed03_idx'),
        ),
    ]
